# Configuration file for gptgodmc
# Make sure you update this before running!

# your OpenAi API key from https://platform.openai.com/api-keys
# the plugin won't work without this

openAiKey: ""

# language in ISO-639 format https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
language: en

# if set to true:
# - When players die they are put in spectator mode
# - When everyone dies the map is reset
# This is the intended way to play
# only set to false for testing and debugging
Rounds: true

# the world the server will load on starting
# worlds are stored in plugins/gptgodmc/worlds
# if empty or invalid the Round System won't work
startingWorld: ""

# if set to true, the plugin will use the newest GPT-4 release
# if set to false the plugin will use GPT 3.5
# GPT 4 is not too expensive these days but you can save a bit of money by using 3.5 instead
use-gpt-4: false

# this will be the prompt provided to Chat-GPT
prompt: "You will roleplay as the god of a small minecraft island world, the players inhabiting the island have no resources. you will recieve information about whats has happened on the island."

# whether or not the mod will make calls to GPT
enabled: true