# Configuration file for gptgodmc
# Make sure you update this before running!

# your OpenAi API key from https://platform.openai.com/api-keys
# the plugin won't work without this

openAiKey: ""

# language in ISO-639 format https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
language: en

# if set to true:
# - When players die they are put in spectator mode
# - When everyone dies the map is reset
# This is the intended way to play
# only set to false for testing and debugging
Rounds: true

# the world the server will load on starting
# worlds are stored in plugins/gptgodmc/worlds
# if empty or invalid the Round System won't work
startingWorld: "island"

# if set to true, the plugin will use the newest stable GPT-4o release
# if set to fals ethe plugin will use GPT-4o-mini
use-gpt-4: true

# whether or not the mod will make calls to GPT
enabled: true

# The gamemode, here are the current options:
# this is case sensitive
#[SANDBOX, DEATHMATCH]
gamemode: SANDBOX


# How long the objectives given by GPT last
# (in minutes)
objectiveDecay: 6

# the amount of time that will pass between calls to ChatGPT (in seconds)
# can't be less that 1 second
# I really don't reccomend going lower than 20
# default 40
rate: 40